/**
 * Every Thread in java has some name it may be provided explicitly by the
 * programmer or automatically generated by JVM
 */

class getting_setting_name
{
    public static void main(String[] args) {
        System.out.println("Current Thread Name: "+Thread.currentThread().getName());
        Thread.currentThread().setName("hrishikesh");//setting name as hrishikesh
        System.out.println("Current Thread Name: " + Thread.currentThread().getName());
    }
}